CREATE DATABASE IF NOT EXISTS hue_calls;

USE hue_calls;
CREATE TABLE IF NOT EXISTS calls (
	id	INTEGER PRIMARY KEY AUTO_INCREMENT,
	success	BOOLEAN,
	dt	DATETIME,
	method	VARCHAR(10),
	uri	VARCHAR(500),
	preset	VARCHAR(20)
);

CREATE USER IF NOT EXISTS "hue"@"172.172.0.1" IDENTIFIED BY "password";
GRANT ALL PRIVILEGES ON hue_calls.* TO "hue"@"172.172.0.1";

